export const LOADING = 'LOADING';
export const LOADING_SUCCESS = 'LOADING_SUCCESS';

/* Landing / Basic */
export const BECOME_A_CHEF = 'BECOME_A_CHEF';
export const LANDING_SIDEBAR = 'LANDING_SIDEBAR';
export const SHOW_FORGOT_PASSWORD = 'SHOW_FORGOT_PASSWORD';
export const SHOW_LOGIN = 'SHOW_LOGIN';
export const SHOW_REGISTER = 'SHOW_REGISTER';

// Login/Register/OTP
export const REGISTER_LOADING = "REGISTER_LOADING";
export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const VERIFY_OTP = "VERIFY_OTP";
export const VERIFY_OTP_SUCCESS = "VERIFY_OTP_SUCCESS";
export const SEND_OTP = "SEND_OTP";
export const SEND_OTP_SUCCESS = "SEND_OTP_SUCCESS";
export const GET_USER = "GET_USER";
export const GET_USER_SUCCESS = "GET_USER_SUCCESS";
export const UPDATE_USER = "UPDATE_USER";
export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";
export const LOGIN = "LOGIN";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGOUT = "LOGOUT";
export const ADDRESS = "ADDRESS";
export const ADDRESS_SUCCESS = "ADDRESS_SUCCESS";
export const ADDRESS_UPDATE = "ADDRESS_UPDATE";
export const ADDRESS_UPDATE_SUCCESS = "ADDRESS_UPDATE_SUCCESS";
export const GET_USER_ADDRESS = "GET_USER_ADDRESS";
export const GET_USER_ADDRESS_SUCCESS = "GET_USER_ADDRESS_SUCCESS";
export const AUTH_ERROR = "AUTH_ERROR";


// Uploads
export const UPLOADS = "UPLOADS";
export const UPLOADS_SUCCESS = "UPLOADS_SUCCESS";
export const UPLOADS_ERROR = "UPLOADS_ERROR";
export const UPLOAD_PROGRESS = "UPLOAD_PROGRESS";

// Dish
export const LOADING_DISH = "LOADING_DISH";
export const LOADING_DISH_SUCCESS = "LOADING_DISH_SUCCESS";
export const LOADING_CUISINES = "LOADING_CUISINES";
export const LOADING_CUISINES_SUCCESS = "LOADING_CUISINES_SUCCESS";
export const LOADING_TYPE = "LOADING_TYPE";
export const LOADING_TYPES_SUCCESS = "LOADING_TYPES_SUCCESS";
export const ADD_DISH = "ADD_DISH";
export const ADD_DISH_SUCCESS = "ADD_DISH_SUCCESS";
export const UPDATE_DISH = "UPDATE_DISH";
export const UPDATE_DISH_SUCCESS = "UPDATE_DISH_SUCCESS";
export const LOADING_DISHES = "LOADING_DISHES";
export const LOADING_DISHES_SUCCESS = "LOADING_DISHES_SUCCESS";
export const LOADING_TIME_SLOTS = "LOADING_TIME_SLOTS";
export const LOADING_TIME_SLOTS_SUCCESS = "LOADING_TIME_SLOTS_SUCCESS";

// Documents
export const ADD_DOCUMENT = "ADD_DISH";
export const ADD_DOCUMENT_SUCCESS = "ADD_DISH_SUCCESS";
export const GET_DOCUMENTS = "GET_DOCUMENTS";
export const GET_DOCUMENTS_SUCCESS = "GET_DOCUMENTS_SUCCESS";
export const DOCUMENTS_ERROR = "DOCUMENTS_ERROR";
export const UPDATE_DOCUMENT = "UPDATE_DOCUMENT";
export const UPDATE_DOCUMENT_SUCCESS = "UPDATE_DOCUMENT_SUCCESS";

// Payments
export const ADD_BANK_DETAILS = "ADD_BANK_DETAILS";
export const ADD_BANK_DETAILS_SUCCCESS = "ADD_BANK_DETAILS_SUCCCESS";
export const GET_BANK_DETAILS = "GET_BANK_DETAILS";
export const GET_BANK_DETAILS_SUCCESS = "GET_BANK_DETAILS_SUCCESS";
export const BANK_DETAILS_ERROR = "DOCUMENTS_ERROR";
export const UPDATE_BANK_DETAILS = "UPDATE_BANK_DETAILS";
export const UPDATE_BANK_DETAILS_SUCCESS = "UPDATE_BANK_DETAILS_SUCCESS";


// Chef
export const LOADING_CHEF = "LOADING_CHEF";
export const LOADING_CHEF_SUCCESS = "LOADING_CHEF_SUCCESS";
export const LOADING_CHEFS = "LOADING_CHEFS";
export const LOADING_CHEFS_SUCCESS = "LOADING_CHEFS_SUCCESS";
export const LOADING_CHEF_DISHES = "LOADING_CHEF_DISHES";
export const LOADING_CHEF_DISHES__SUCCESS = "LOADING_CHEF_DISHES__SUCCESS";


//User
export const LOADING_USER_PROFILE = "LOADING_USER_PROFILE";
export const LOADING_USER_PROFILE_SUCCESS = "LOADING_USER_PROFILE_SUCCESS";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";
export const UPDATE_USER_PROFILE_SUCCESS = "UPDATE_USER_PROFILE_SUCCESS";


// Cart
export const LOADING_CART = "LOADING_CART";
export const LOADING_CART_SUCCESS = "LOADING_CART_SUCCESS";
export const ADD_TO_CART = "ADD_TO_CART";
export const ADD_TO_CART_SUCCESS = "ADD_TO_CART_SUCCESS";
export const UPDATE_CART = "UPDATE_CART";
export const UPDATE_CART_SUCCESS = "UPDATE_CART_SUCCESS";
export const CART_ERROR = "CART_ERROR";
export const DELETE_CART = "DELETE_CART";
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS";


// Order
export const LOADING_ORDERS = "LOADING_ORDERS";
export const LOADING_ORDERS_SUCCESS = "LOADING_ORDERS_SUCCESS";
export const PLACE_ORDER = "PLACE_ORDER";
export const PLACE_ORDER_SUCCESS = "PLACE_ORDER_SUCCESS";
export const UPDATE_ORDER = "UPDATE_ORDER";
export const UPDATE_ORDER_SUCCESS = "UPDATE_ORDER_SUCCESS";
export const ORDER_ERROR = "ORDER_ERROR";
export const DELETE_ORDER = "DELETE_ORDER";
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS";


// Address
export const LOADING_ADDRESS = "LOADING_ADDRESS";
export const LOADING_ADDRESS_SUCCESS = "LOADING_ADDRESS_SUCCESS";
export const ADD_ADDRESS = "ADD_ADDRESS";
export const ADD_ADDRESS_SUCCESS = "ADD_ADDRESS_SUCCESS";
export const UPDATE_ADDRESS = "UPDATE_ADDRESS";
export const UPDATE_ADDRESS_SUCCESS = "UPDATE_ADDRESS_SUCCESS";
export const ADDRESS_ERROR = "ADDRESS_ERROR";
export const DELETE_ADDRESS = "DELETE_ADDRESS";
export const DELETE_ADDRESS_SUCCCESS = "DELETE_ADDRESS_SUCCCESS";



